In [92]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/Users/pj/Documents/GitHub/Data-Notebooks/data/3Year_Projections.csv')
data.info()
clean = data.dropna()
clean

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Budget Items  53 non-null     object
 1   Year 1        52 non-null     object
 2   Year 2        50 non-null     object
 3   Year 3        50 non-null     object
dtypes: object(4)
memory usage: 1.8+ KB

,Budget Items,Year 1,Year 2,Year 3
0,Total Revenue,"$27,543,750.00","$28,775,875.00","$29,985,225.00"
1,Initial Membership Chip/ Tournament 1 Sale,"$4,312,500.00",0,0
2,Equal Value Tournaments,"$21,562,500.00","$25,875,000.00","$25,875,000.00"
3,Merchandise,"$15,000.00","$20,000.00","$27,000.00"
4,NFT Wearables,"$225,000.00","$500,000.00","$750,000.00"
5,Units Sold,1500,2500,3000
6,Average Cost of Units,$150.00,$200.00,$250.00
7,NFT Secondary Sales,"$1,428,750.00","$2,380,875.00","$3,333,225.00"
9,Cost of Sales,"$18,137,000.00","$18,140,000.00","$18,149,000.00"
10,Tournament Payouts,"$18,135,000.00","$18,135,000.00","$18,135,000.00"
11,Contract Deployments,"$2,000.00","$5,000.00","$14,000.00"
13,Gross Revenue,"$9,406,750.00","$10,635,875.00","$11,836,225.00"
14,Gross Margin,34%,37%,39%
15,Operating Expenses,"$2,679,050.00","$3,565,900.00","$4,573,290.00"
16,Poker Software,"$12,000.00","$12,000.00","$12,000.00"
17,Website Development,"$5,000.00","$2,000.00","$2,000.00"
18,Attorney and Legal Fees,"$551,800.00","$556,650.00","$569,040.00"
19,Incorporation,"$7,500.00",0,0
20,Gaming License,"$519,300.00","$521,650.00","$524,040.00"
21,Copyrights/ Patents,"$25,000.00","$35,000.00","$45,000.00"
22,DAO Funding,"$900,000.00","$1,500,000.00","$2,100,000.00"
23,Marketing Budget,"$130,000.00","$155,000.00","$240,000.00"
24,Publications,"$30,000.00","$20,000.00","$20,000.00"
25,Influencer Deals,"$50,000.00","$75,000.00","$150,000.00"
26,Paid Social Ads,"$50,000.00","$60,000.00","$70,000.00"
27,Salary & Wages,"$900,250.00","$1,070,250.00","$1,380,250.00"
28,Founders,"$750,000.00","$750,000.00","$750,000.00"
29,Developers,"$50,000.00","$200,000.00","$500,000.00"
30,Community Management Team,"$100,250.00","$120,250.00","$130,250.00"
31,Discord Manager / Team,"$40,000.00","$60,000.00","$70,000.00"
32,Marketing Coordinator,"$60,250.00","$60,250.00","$60,250.00"
33,Technology/ Hardware,"$20,000.00","$20,000.00","$20,000.00"
34,The Raining Season Partnership,"$160,000.00","$250,000.00","$250,000.00"
35,Project Devlopment Cost,"$10,000.00",0,0
36,Foundation Donation,"$150,000.00","$250,000.00","$250,000.00"
37,Bad Debt,0,0,0
38,Amortization of Other Current Assets,0,0,0
39,EBITDA,"$6,727,700.00","$7,069,975.00","$7,262,935.00"
40,Additional Expenses,0,0,0
41,Total Depreciation,0,0,0
42,Gain or loss form sales of Assets,0,0,0
43,EBIT,"$6,572,450.00","$6,889,725.00","$7,062,685.00"
44,Interest Expenses,0,0,0
45,EBT,"$6,572,450.00","$6,889,725.00","$7,062,685.00"
46,Income Tax Expenses,0,0,0
48,Total Expenses,"$2,679,050.00","$3,565,900.00","$4,573,290.00"
49,Net Income,"$6,572,450.00","$6,889,725.00","$7,062,685.00"
50,Retained Earning Opening,0,"$4,982,262.50","$10,371,987.50"
51,Founder's Distribution,"$1,500,000.00","$1,500,000.00","$1,500,000.00"
54,Retained Earning Closing,"$4,982,262.50","$10,371,987.50","$15,934,672.50"

In [93]:
for col in clean.columns[1:]: 
    clean[col] = clean[col].astype(str).str.replace('$', "").str.replace(',', "").str.replace('%', "") 
    clean[col] = pd.to_numeric(clean[col]) 
clean

/var/folders/k3/5g1jby35685dbshz0tv3c50h0000gn/T/ipykernel_99007/1857462354.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  clean[col] = clean[col].astype(str).str.replace('$', "").str.replace(',', "").str.replace('%', "")
/var/folders/k3/5g1jby35685dbshz0tv3c50h0000gn/T/ipykernel_99007/1857462354.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean[col] = clean[col].astype(str).str.replace('$', "").str.replace(',', "").str.replace('%', "")
/var/folders/k3/5g1jby35685dbshz0tv3c50h0000gn/T/ipykernel_99007/1857462354.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean[col] = pd.to_numeric(clean[col])

,Budget Items,Year 1,Year 2,Year 3
0,Total Revenue,27543750.0,28775875.0,29985225.0
1,Initial Membership Chip/ Tournament 1 Sale,4312500.0,0.0,0.0
2,Equal Value Tournaments,21562500.0,25875000.0,25875000.0
3,Merchandise,15000.0,20000.0,27000.0
4,NFT Wearables,225000.0,500000.0,750000.0
5,Units Sold,1500.0,2500.0,3000.0
6,Average Cost of Units,150.0,200.0,250.0
7,NFT Secondary Sales,1428750.0,2380875.0,3333225.0
9,Cost of Sales,18137000.0,18140000.0,18149000.0
10,Tournament Payouts,18135000.0,18135000.0,18135000.0
11,Contract Deployments,2000.0,5000.0,14000.0
13,Gross Revenue,9406750.0,10635875.0,11836225.0
14,Gross Margin,34.0,37.0,39.0
15,Operating Expenses,2679050.0,3565900.0,4573290.0
16,Poker Software,12000.0,12000.0,12000.0
17,Website Development,5000.0,2000.0,2000.0
18,Attorney and Legal Fees,551800.0,556650.0,569040.0
19,Incorporation,7500.0,0.0,0.0
20,Gaming License,519300.0,521650.0,524040.0
21,Copyrights/ Patents,25000.0,35000.0,45000.0
22,DAO Funding,900000.0,1500000.0,2100000.0
23,Marketing Budget,130000.0,155000.0,240000.0
24,Publications,30000.0,20000.0,20000.0
25,Influencer Deals,50000.0,75000.0,150000.0
26,Paid Social Ads,50000.0,60000.0,70000.0
27,Salary & Wages,900250.0,1070250.0,1380250.0
28,Founders,750000.0,750000.0,750000.0
29,Developers,50000.0,200000.0,500000.0
30,Community Management Team,100250.0,120250.0,130250.0
31,Discord Manager / Team,40000.0,60000.0,70000.0
32,Marketing Coordinator,60250.0,60250.0,60250.0
33,Technology/ Hardware,20000.0,20000.0,20000.0
34,The Raining Season Partnership,160000.0,250000.0,250000.0
35,Project Devlopment Cost,10000.0,0.0,0.0
36,Foundation Donation,150000.0,250000.0,250000.0
37,Bad Debt,0.0,0.0,0.0
38,Amortization of Other Current Assets,0.0,0.0,0.0
39,EBITDA,6727700.0,7069975.0,7262935.0
40,Additional Expenses,0.0,0.0,0.0
41,Total Depreciation,0.0,0.0,0.0
42,Gain or loss form sales of Assets,0.0,0.0,0.0
43,EBIT,6572450.0,6889725.0,7062685.0
44,Interest Expenses,0.0,0.0,0.0
45,EBT,6572450.0,6889725.0,7062685.0
46,Income Tax Expenses,0.0,0.0,0.0
48,Total Expenses,2679050.0,3565900.0,4573290.0
49,Net Income,6572450.0,6889725.0,7062685.0
50,Retained Earning Opening,0.0,4982262.5,10371987.5
51,Founder's Distribution,1500000.0,1500000.0,1500000.0
54,Retained Earning Closing,4982262.5,10371987.5,15934672.5

In [91]:
bar = sns.barplot(data=clean,
            x=clean.loc[0][1:],
            y=clean.columns)
bar

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().